docker_sd_configs:
  - host: unix:///var/run/docker.sock
    refresh_interval: 5s
    filters:
      - name: label
        values: ["com.docker.compose.service"]

relabel_configs:
  - source_labels: ['__meta_docker_container_name']
    target_label: 'container_name'
  - source_labels: ['__meta_docker_container_id']
    target_label: 'container_id'
  - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
    target_label: 'service'
  - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
    target_label: 'project' 