server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
    - targets:
        - localhost
      labels:
        job: docker
        __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            log: log
            attrs: attrs
      - docker: {}
      - regex:
          expression: '/var/lib/docker/containers/(?P<container_id>[^/]+)/.*'
          source: filename
      - regex:
          expression: '.*"Name":"(?P<container_name>/[^"]+)".*'
          source: attrs.container_config
      - template:
          source: container_name
          template: '{{ if .container_name }}{{ trimPrefix "/" .container_name }}{{ else }}unknown{{ end }}'
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          container_id:
          container_name:
          filename:
          stream:
      - output:
          source: log

  - job_name: docker-discovery
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_id']
        target_label: 'container_id'
    pipeline_stages:
      - docker: {}
      - timestamp:
          source: time
          format: RFC3339Nano
      - output:
          source: log

  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
    pipeline_stages:
      - output:
          source: message
